### ISSUE TITLE
No apk

### ISSUE THREAD

**Issue by ghost** [DrMint/Okuma-Reader#5]
I would love to use this app but there is no download for the apk

**Comment by DrMint** [comment]
Hi! I know I already answered you on Discord, nonetheless I'm answering here too in case someone else is looking for an apk. So Okuma-Reader is a web app that needs to be hosted somewhere and accessed in the browser. It is not a native Android app which is why there is no apk. I guess Okuma could be converted into a native app, and there could be a use case for it. I personally think it would be more interesting to make the web app a PWA (progressive web app). This way it's kind of the best of both worlds: you have an online web app which only happens to work offline.
There are a couple challenges to overcome like being able to download books locally (for offline usage), and possibly open local archives too.
